Add missing definitions TypeScript file for chrome.metricsPrivate
We were lacking this on our preprocessed overrides for JS files, that
was causing the following build error in people_page.ts, twice:

  error TS2339: Property 'metricsPrivate' does not exist on type 'typeof chrome'.

Add the definition to our BUILD.gn file to fix the issue.