[cr145] Fixes logging of CopyFromSurfaceError build error.
 ../../brave/components/ai_chat/content/browser/page_content_fetcher.cc(473,16): error: invalid operands to binary expression ('basic_ostream<char,
 std::char_traits<char>>' and 'const content::CopyFromSurfaceError')
   472 |     LOG(ERROR) << "RenderWidgetHostView::CopyFromSurface failed with: "
       |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   473 |                << result.error();
       |                ^  ~~~~~~~~~~~~~~
 ../../third_party/libc++/src/include/__ostream/basic_ostream.h(349,55): note: candidate function template not viable: no known conversion from 'const
 content::CopyFromSurfaceError' to 'char' for 2nd argument

Chromium change:

https://source.chromium.org/chromium/chromium/src/+/9d2b3244101ccd0eb8321d3027c648ec4a1b14e2

commit 9d2b3244101ccd0eb8321d3027c648ec4a1b14e2
Author: Dave Tapuska <dtapuska@chromium.org>
Date:   Thu Jan 15 07:32:24 2026 -0800

    Set timeout from multi source page context fetcher

    - Change the result code on CopyFromSurface so we can log a uma histogram
    instead of an arbitrary string
    - Pass timeout to viz, set the browser side timeout to be 500ms later to
    give the IPC enough time.

    Bug: b:447589565