[cr149][WIP] TypeScript compiler updated to `6.0.2`
Commenting off the offending inclusions to get the code to build.

```
RuntimeError: Command '/home/redacted/dev/brave-dev/src/third_party/node/linux/node-linux-x64/bin/node /home/redacted/dev/brave-dev/src/third_party/node/node_modules/typescript/bin/tsc --project gen/ui/webui/resources/cr_elements/tsconfig_build_ts.json' failed
stdout:
gen/ui/webui/resources/cr_elements/preprocessed/cr_button/cr_button.ts:6:8 - error TS2882: Cannot find module or type declarations for side-effect import of '//resources/brave/leo.bundle.js'.

6 import '//resources/brave/leo.bundle.js';
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

gen/ui/webui/resources/cr_elements/preprocessed/cr_icon/cr_icon.ts:11:8 - error TS2882: Cannot find module or type declarations for side-effect import of '//resources/brave/leo.bundle.js'.

11 import '//resources/brave/leo.bundle.js';
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

gen/ui/webui/resources/cr_elements/preprocessed/cr_toggle/cr_toggle.ts:6:8 - error TS2882: Cannot find module or type declarations for side-effect import of '//resources/brave/leo.bundle.js'.

6 import '//resources/brave/leo.bundle.js'
         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 3 errors in 3 files.

Errors  Files
     1  gen/ui/webui/resources/cr_elements/preprocessed/cr_button/cr_button.ts:6
     1  gen/ui/webui/resources/cr_elements/preprocessed/cr_icon/cr_icon.ts:11
     1  gen/ui/webui/resources/cr_elements/preprocessed/cr_toggle/cr_toggle.ts:6
```

Chromium changes:
https://chromium.googlesource.com/chromium/src/+/83a142eb9a629d7247fc66944007f682de3a63fd

commit 83a142eb9a629d7247fc66944007f682de3a63fd
Author: dpapad <dpapad@chromium.org>
Date:   Mon Apr 6 20:34:40 2026 -0700

    [Reland] WebUI: Update TypeScript compiler from 5.9.3 to 6.0.2.

    Reland notes: Revert was caused by a bug in
    @typescript-eslint/typescript-estree v8.58.0 which only triggers in a
    couple post commit bots. The problem was worked around in the precursor
    https://crrev.com/c/7727885.

    Specifically:
     - Removing chrome/browser/resources/glic/url_pattern.d.ts since these
       are now part of TS compiler's default definitions.
     - Changing 'module' to 'namespace' in
       components/translate/ios/browser/resources/translate_ios.ts, since
       usage of the deprecated "module" now throws an error [1].
     - Updating third_party/node/patches/typescript.patch to restore the
       type of `HTMLElement#hidden` to just `boolean` instead of
       `"boolean|"until-found"` since the latter causes a lot of TS errors
       in WebUI tests. These will be addressed in a follow-up.
     - Removing newly unnecessary definitions in
       tools/typescript/definitions/pending.d.ts.

    CrOS changes
     - Adding 'ignoreDeprecations' flag in CrOS targets that fail otherwise
       due to using stuff that is officially deprecated in v6:
       - chrome/browser/resources/chromeos/accessibility/
       - third_party/cros-components/
       - third_party/material_web_components/
     - Fixing newly surfaced type errors in ash/webui/media_app_ui/ and
       ui/file_manager/

    [1] https://devblogs.microsoft.com/typescript/announcing-typescript-6-0/#deprecated:-legacy-module-syntax-for-namespaces

    Bug: 423789047, 484345339, 468035608
    Change-Id: Ie7043b93434549fb35c2c934bfc5c6c679b5d20e
    Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7722202
    Commit-Queue: François Degros <fdegros@chromium.org>
    Reviewed-by: Rebekah Potter <rbpotter@chromium.org>
    Reviewed-by: Camden Bickel <cambickel@google.com>
    Reviewed-by: James Hawkins <jhawkins@chromium.org>
    Reviewed-by: François Degros <fdegros@chromium.org>
    Cr-Commit-Position: refs/heads/main@{#1610513}