[cr141] Added missing header for NavigationController
Otherwise there is a build error:
../../brave/browser/speedreader/speedreader_tab_helper.cc:275:52: error: member access into incomplete type 'NavigationController'
  275 |   if (auto* entry = web_contents()->GetController().GetLastCommittedEntry()) {
      |                                                    ^
../../content/public/browser/render_frame_host.h:121:7: note: forward declaration of 'content::NavigationController'
  121 | class NavigationController;
      |       ^
../../brave/browser/speedreader/speedreader_tab_helper.cc:281:34: error: member access into incomplete type 'NavigationController'
  281 |   web_contents()->GetController().Reload(content::ReloadType::NORMAL, false);
      |                                  ^
../../content/public/browser/render_frame_host.h:121:7: note: forward declaration of 'content::NavigationController'
  121 | class NavigationController;
      |       ^
../../brave/browser/speedreader/speedreader_tab_helper.cc:402:48: error: member access into incomplete type 'NavigationController'
  402 |   auto* entry = web_contents()->GetController().GetLastCommittedEntry();
      |                                                ^
../../content/public/browser/render_frame_host.h:121:7: note: forward declaration of 'content::NavigationController'
  121 | class NavigationController;