[iOS] Workaround an upstream bug with credential provider extension.
We build with `ios_enable_credential_provider_extension = false` but
the recent upstream change causes errors in this configuration:

Initially:
ERROR Unresolved dependencies.
//ios/chrome/app:credential_provider_migrator_app_agent(//build/toolchain/ios:ios_clang_x64)
  needs //ios/chrome/browser/credential_provider:credential_provider(//build/toolchain/ios:ios_clang_x64)

And, also:
../../ios/chrome/app/main_controller.mm:663:29: error: use of undeclared identifier 'CredentialProviderAppAgent'
  [self.appState addAgent:[[CredentialProviderAppAgent alloc] init]];
                            ^
1 error generated.

Filed an upstream bug with this info:
https://bugs.chromium.org/p/chromium/issues/detail?id=1245295

Temporary patched to work around the build errors.

Chromium change:

https://chromium.googlesource.com/chromium/src.git/+/b32f389ea82506054ab7fda2ce6abbabe0c2a797

commit b32f389ea82506054ab7fda2ce6abbabe0c2a797
Author: Javier Ernesto Flores Robles <javierrobles@chromium.org>
Date:   Tue Aug 10 18:41:12 2021 +0000

    [iOS][Credential-Provider] Import CPE passwords to password manager

    Move Credential Provider Extension (CPE) passwords from temporal
    storage to password manager.

    CPE stores the password in the Keychain already, so there is no need
    to re-encrypt passwords.

    Bug: 1224983